### ISSUE TITLE
Suggested notes for installation

### ISSUE THREAD

**Issue by robrys** [theJollySin/mazelib#82]
In order to get installation to work on any of my systems, I've had to do the following:

before "python setup.py build_ext --inplace":
1) export CFLAGS="-I /usr/local/lib/python2.7/site-packages/numpy/core/include"

before "python setup.py install":
2) pip install cython==0.21
the mazelib seems to break with other versions of cython

3) remove "mazelib.utils" from the "packages = [ ... ]" list in setup.py,
since it no longer exists

Thanks for the killer work!

**Comment by theJollySin** [comment]
Sorry, no one has ever noticed one of my projects before, I didn't notice the ticket. I will do those.

I wanted to break the project into Python v2 and Cython tags because I know some people will just want the pure Python versions to learn how the algorithms work for their own projects.  It is good to know that you are interested in the Cython version, perhaps that will still be the master tag.
