### ISSUE TITLE
name 'MazeArray' is not defined

### ISSUE THREAD

**Issue by Fineas** [theJollySin/mazelib#90]
```
    g = MazeArray(43, 43)
NameError: name 'MazeArray' is not defined
```
I keep getting this error, and after searching threw the project, indeed, I found no mention of MazeArray.

**Comment by theJollySin** [comment]
You are exactly right, that documentation was out of date.  I have updated the documentation to match the current methodology.

For background, I originally tried to make it so this project didn't require NumPy as an import, and I had to build the clunky `MazeArray` class to handle the load.  I have since switched to using standard 2D NumPy arrays, as most users will be familiar with them and it should make the progress more accessible.
