### ISSUE TITLE
WallFollower() wrong solutions

### ISSUE THREAD

**Issue by nfsrules** [theJollySin/mazelib#93]
Hi, thanks for this great contribution.

I've noted that WallFollower() sometimes produces incorrect or non feasible solutions. It would be nice to check the implementation.

Best regards

**Comment by theJollySin** [comment]
I'll take a look at it, thanks.

**Comment by theJollySin** [comment]
The problem, of course, could be that the maze you were trying to solve with WallFollower was malformed.  It would be handy if I could reproduce the issue.  I am trying, but no luck so far.

**Comment by theJollySin** [comment]
Okay, I managed to reproduce this bug, at least sort of.
I used CellularAutomaton to generate the maze, and then WallFollower to solve it.  And then WallFollower failed.

There is already a ticket open for CellularAutomaton though.  The problem is it does not *always* generate perfect mazes. That is, sometimes it generates mazes with multiple solutions.  And WallFollower can not solve mazes with more than one solution.

In this instance, I will say this is a bug with CellularAutomaton, and I have a bug ticket open for that.  I will test some more.

**Comment by theJollySin** [comment]
Okay, after a lot of testing I have found that `WallFollower` always works against "perfect" mazes.  That is, a maze that has one and only one solution. 

This is explicitly called out in the documentation.  But I guess that is a finer point of maze algorithms that will be lost on most people who definitely aren't reading my documentation.

This leaves me with two solutions:

1) Remove all maze-solving algorithms that can not solve imperfect mazes (currently this is only `WallFollower`).
2) Explicitly raise `Warning`s if a user tries to use `WallFollower` or the like on a maze generated with an imperfect algorithm.

I like the idea of supporting all maze generating/solving algorithms, including imperfect ones.  So I guess I would go with (2).

But this will probably continue to confuse people, so maybe I should go with (1).

What do you think?

**Comment by nfsrules** [comment]
Hello @theJollySin, thank you for the effort you have put into solving this problem.
In my case, I was using Prims() as a generator and WallFollower() as a solver. I changed it to ShortestPath() and it worked like a charm (as expected).

As you pointed out, I didn't see that WallFollower() could fail when the maze isn't perfect. I realized there was a problem when inspecting the results.

I'd go with option (2), you could raise a warning when creating the WallFollower() instance. I find it interesting that you have implemented a whole suite of solvers, even if one of them, in a particular situation may fail. It's your decision, though.

Nelson

**Comment by theJollySin** [comment]
@nfsrules  Oh, you used Prims. That's different.  I will have to look into that.

I think the problem is that `WallFollower` was meant to be the naive way people solve mazes in the real world when walking through a maze.  You just take every right turn and for a "perfect" maze, you will always find your way out.  It will just take forever.  

Maybe I should only include the high-quality maze solvers though, and not the naive one.

Thanks for the response!

**Comment by theJollySin** [comment]
@nfsrules I am going to remove WallFollower and slightly modify Chain (as it uses a minified version of WallFollower).

Basically, I think the API for mazelib would be simpler to understand if the user didn't have to know which maze generators could work with which maze solvers.  So I am going to support all maze generating algorithms going forward, but only maze solving algorithms which are universal (work for all mazes).

Just FYI.  Change coming soon.
