### ISSUE TITLE
Get test coverage above 95%

### ISSUE THREAD

**Issue by theJollySin** [theJollySin/mazelib#95]
@doctorcolossus reported that his teachers wouldn't want to use mazelib unless its test coverage was over 95% and I am currently at 85%.  SO, it's time to beef up these tests a bit.  Shouldn't be hard.

**Comment by doctorcolossus** [comment]
Thank you so much.

**Comment by doctorcolossus** [comment]
serendipitous that 95% code coverage was your 95th issue :smile:

**Comment by theJollySin** [comment]
@doctorcolossus  LOL   I hadn't noticed!

Seriously though, I think 95% is too high a bar.  You can get up your tests to cover 100% of the lines of the code, but still only touch 50% of the functionality of the program.  Maybe setting the bar at 70-80% is a good idea. But at some point, you are forcing people just to meet some lame "# of lines covered" metric instead of actually designing tests to cover the important functionality.

Don't drink the Kool-Aid!

![Don't drink the Kool-Aid](https://frinkiac.com/img/S05E03/568000.jpg)

`#endrant`

**Comment by doctorcolossus** [comment]
Yeah, I completely agree - it's an exaggeration. However, I think the idea of the class is to expose us to test-driven development and they just set the bar absurdly high to force us to get into that habit. I personally had never bothered writing any unit tests at all in the past, and I definitely understand the how and why much better after getting some hands-on experience.

On the other hand, I do think it's ridiculous to demand the same rigor of external libraries we pull in. It's like you say - 95% or even 100% coverage still doesn't guarantee that the unit tests check everything they should!

I think in this case, the scrutiny on our use of mazelib was mostly political, in an effort to maintain a guise of consistency. There was some drama at the beginning of the project, since I had built a parser for the game built on the natural language parser spacy, and was told I had to scrap it, ostensibly because spacy has only ~75% code coverage. I think the actual reason was because the LAs felt my code was too complex for my teammates, who aren't as proficient in python. :expressionless: That was sad, but c'est la vie.
